[[NEO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "false"
git-tree-sha1 = "25b852bb3eb6612a24dd54358ceaa9025aa2a6de"
lazy = true
libc = "glibc"
os = "linux"

    [[NEO.download]]
    sha256 = "2fde0b7ba394402134457754809c0b62374a14b7fd0983a3ac7cc94007ebc327"
    url = "https://github.com/JuliaBinaryWrappers/NEO_jll.jl/releases/download/NEO-v25.44.36015+0/NEO.v25.44.36015.x86_64-linux-gnu-cxx11-debug+false.tar.gz"
[[NEO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
debug = "true"
git-tree-sha1 = "9076237efdb083324ab1db54456e32623c5396c7"
lazy = true
libc = "glibc"
os = "linux"

    [[NEO.download]]
    sha256 = "5a596fd27eb9876156d89867387ebd930282c4b3a98bcb42ca265a3acae4ccb4"
    url = "https://github.com/JuliaBinaryWrappers/NEO_jll.jl/releases/download/NEO-v25.44.36015+0/NEO.v25.44.36015.x86_64-linux-gnu-cxx11-debug+true.tar.gz"
